"""add workspaces and auth fields on users

Revision ID: 0418c03c28a9
Revises: e0e98ed3cc04
Create Date: 2026-08-26 19:39:44.574109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0418c03c28a9'
down_revision: Union[str, Sequence[str], None] = 'e0e98ed3cc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.add_column('users', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_workspace_id_workspaces'), 'users', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_workspace_id_workspaces'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
