"""remove workspace concept - user-owned data only

Revision ID: 1337cab1aeb5
Revises: 0418c03c28a9
Create Date: 2026-08-27 07:49:33.527702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1337cab1aeb5'
down_revision: Union[str, Sequence[str], None] = '0418c03c28a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - reordered by hand ###
    # Must drop the FK/column on `users` that references `workspaces`
    # BEFORE dropping `workspaces` itself -- Postgres refuses to drop a
    # table another table still has a foreign key pointing at.
    # Autogenerate emitted these in the wrong order; verified this fix
    # against a real Postgres instance before shipping it.
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_constraint(op.f('fk_users_workspace_id_workspaces'), 'users', type_='foreignkey')
    op.drop_column('users', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - reordered by hand ###
    op.create_table('workspaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.add_column('users', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_workspace_id_workspaces'), 'users', 'workspaces', ['workspace_id'], ['id'])
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    # ### end Alembic commands ###